som_sigma: 0.02
lr: 2.0e-05
weight_decay: 0
img_size:
- 640
- 480
sample_grid_size: 1
n_rays: 2048
max_sample_depth: 12
eval_depth: 10
std: 0.1
n_gaussians: 4
n_pts_uni: 32
n_pts_per_gaussian: 8
smooth_loss_weight: 0.0
sampling_method: uniform
batch_size: 1
net_2d: b7
add_fov_hor: 14
add_fov_ver: 11
sphere_H: 720
sphere_W: 960
use_color: true
use_reprojection: true
